mar10/wsgidav

wsgidav/request_server.py
https://github.com/mar10/wsgidav/issues/15
Applies a workaround for the apparent lacking protocol compliance in
Finder when doing chunked uploading.
=> Fix Mac Finder upload and copy as described in issue 15

doc/annotated_wsgidav.conf, wsgidav.conf.sample, wsgidav/dav_provider.py, wsgidav/fs_dav_provider.py
Add configurable support for setting last modified file/directory timestamps. E.g. when a user mounts a DAV share and runs touch or copy/rsync commands with preserve timestamps flags to destination files or directories there. Not enabled by default since it may not be compliant with RFC 4918.
This is a proposed patch for issue #19 .
Tested to work as expected on files and directories with the new mutable_live_props configuration unset, set to [] and 
mutable_live_props = ["{DAV:}getlastmodified"] 
Please comment or consider for merging.
Cheers, Jonas
=> Add configurable support for setting last modified file/directory timestamps (issue #19)

requirements-dev.txt
WebTest dependency uses =~ to specify the version but it should be ~=
=> Fix typo in requeriments-dev.txt

tests/test_lock_manager.py
This fixes the lock manager test for python2 and python3
=> Ensure owner property of lock manager is always bytes

wsgidav/wsgidav_app.py
When getting a path that doesn't match any provider, an unhelpful error is returned:
```shell
Traceback (most recent call last):
File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
self.finish_response()
File "/usr/lib/python2.7/wsgiref/handlers.py", line 131, in finish_response
self.close()
File "/usr/lib/python2.7/wsgiref/simple_server.py", line 33, in close
self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
127.0.0.1 - - [09/Sep/2016 15:27:45] "GET / HTTP/1.1" 500 59
```
This is hiding a `KeyError` when `share` is not in `self.providerMap`:
```python
share_data = self.providerMap.get(share)
-        environ["wsgidav.provider"] = share_data['provider']
```
With this patch a 404 is returned.
=> Fix KeyError for non-matching share.

CHANGELOG.md, requirements.txt, setup.py, wsgidav/xml_tools.py
By default `lxml.etree` and `xml.etree` are not safe when parsing untrusted user input. This PR uses [defusedxml](https://pypi.python.org/pypi/defusedxml) to wraps those libraries, applying safe defaults, thus preventing several attack vectors.
=> Use defusedxml for safe xml parsing

.travis.yml, install_litmus.sh, tests/test_litmus.py
I noticed that litmus is failing on the master branch but we did not notice which changeset broke it as travis is not executing the litmus test suite. 
So I'm adding a script to install litmus and modified the .travis.yml file in order to run it before running the test.
=> Run litmus test suite on travis

wsgidav/addons/couch_property_manager.py, wsgidav/addons/hg_dav_provider.py, wsgidav/addons/mongo_property_manager.py, wsgidav/addons/mysql_dav_provider.py, wsgidav/addons/nt_domain_controller.py, wsgidav/dav_error.py, wsgidav/dav_provider.py, wsgidav/dir_browser.py, wsgidav/domain_controller.py, wsgidav/error_printer.py, wsgidav/fs_dav_provider.py, wsgidav/http_authenticator.py, wsgidav/lock_manager.py, wsgidav/lock_storage.py, wsgidav/property_manager.py, wsgidav/request_resolver.py, wsgidav/request_server.py, wsgidav/samples/dav_provider_tools.py, wsgidav/samples/virtual_dav_provider.py, wsgidav/server/ext_wsgiutils_server.py, wsgidav/server/run_reloading_server.py, wsgidav/server/run_server.py, wsgidav/util.py, wsgidav/wsgidav_app.py, wsgidav/xml_tools.py
This is the result after some manual fixes: 
22    E128 continuation line under-indented for visual indent
13    E501 line too long (153 > 99 characters)
2     E713 test for membership should be 'not in'
1     F401 'wsgidav._version.__version__' imported but unused
4     F811 redefinition of unused 'etree' from line 15
2     F821 undefined name 'unicode'
44
I think all the ones are missing there are excepts or comment code. So I will prefer you to review them manually.
=> Manual pep8 fixes

wsgidav/request_server.py
Now that we allow method overrides, we still have to add POST to the list of possible methods so that it can be used. (Currently `doPOST()` never gets called).
=> Allow POST implementations

wsgidav/dav_provider.py
Fixes removeProperty call to not lose dryRun, otherwise removeProperty is called twice for real
=> PROPPATCH atomicity with removeProperty

wsgidav/debug_filter.py
This is giving me an exception when running as wsgi app under eventlet,
with Python3. A variable is not defined instead of empty string in this
case causing the error. The patch avoids the error in this case.
=> Prevent error when missing environment variable.

wsgidav/dir_browser.py, wsgidav/domain_controller.py, wsgidav/wsgidav_app.py
Supply the same default as Python will - 'ASCII' - in this case.
I ran into this issue when running wsgidav within PyCharm.  Python does not detect the output encoding and `sys.stdout.encoding` is `None`, which causes an error inside `safeReEncode`.
=> Don't assume sys.stdout.encoding is not None

wsgidav/addons/couch_property_manager.py, wsgidav/addons/mongo_property_manager.py, wsgidav/dav_provider.py, wsgidav/fs_dav_provider.py, wsgidav/property_manager.py
The DAV provider already has access to the environ, but the
PropertyManager didn't until now.  In my system both of these need to
know about the user making the request for access control / file
resolution purposes.
=> Give custom PropertyManager implementations access to the environ

wsgidav.conf, wsgidav.conf.sample, wsgidav/request_server.py
Implementing custom response headers as per #90 
Custom headers can be set via conf file. Response headers must be a list of header-name / header-value:
```
response_headers = [('Access-Control-Allow-Origin', 'http://example.org')]
```
=> Custom response headers

wsgidav/request_server.py
Added support to handle large files being copied into webdav on a mac.
Currently if a large file is uploaded to webdav and HTTP_TRANSFER_ENCODING is chunked, then the whole file is read into memory first.
Modified logic to read at most up to the specified block size.
=> Added support for large files on the mac.

wsgidav/dir_browser.py
QUERY_STRING not always in environment
Tested with wsgi server bjoern
=> Fixing assumption that QUERY_STRING in environment

wsgidav/request_server.py
I tried to get the virtual_dav_provider.py example working with WsgiDAV/2.3.0 Cheroot/6.2.4 Python/3.6.3 .
However, I got an error when accessing the virtual meta data files, e.g. .Info.html:
<123145538461696> [20:55:40.741] wsgidav:  ErrorPrinter: caught Exception
Traceback (most recent call last):
File "/anaconda/envs/python3/lib/python3.6/site-packages/wsgidav/error_printer.py", line 55, in __call__
for v in app_iter:
File "/anaconda/envs/python3/lib/python3.6/site-packages/wsgidav/request_resolver.py", line 206, in __call__
for v in app_iter:
File "/anaconda/envs/python3/lib/python3.6/site-packages/wsgidav/request_server.py", line 129, in __call__
for v in app_iter:
File "/anaconda/envs/python3/lib/python3.6/site-packages/wsgidav/request_server.py", line 1526, in _sendResource
assert …
=> Fixed python3 error

wsgidav/samples/virtual_dav_provider.py
Second attempt to get virtual_dav_provider.py running under python 3 after pull request #98 didn't work. Tested with python 3.6 and 2.7.
=> python3 bug fix (second attempt): WSGI expects binary instead of str

wsgidav/request_server.py
When creating an empty temporaryfile from python3 and try to upload such file to wsgidav, wsgidav fails:
```invalid literal for int() with base 16: b''```
This fixes such condition, though I don't know why `leng(buf)` is not used in a first place.
=> Checking if buffer is empty bytestring

wsgidav/wsgidav_app.py
When we use pythonw.exe(the python interpreter without GUI on windows),  sys.stdout will be set to none. That will cause an AttributeError which blocking all wsgidav services.
=> fix an issue when 'sys.stdout' is none

wsgidav/request_server.py, wsgidav/util.py
https://github.com/mar10/wsgidav/blob/cec0d84222fc24bea01be1cea91729001963f172/wsgidav/request_server.py#L1551
We should cast to an int here, as the dav_provider never specified that last_modified has to be a whole number. I'm currently using datetime.timestamp() which is returning a float.
This fixed an error for me, where Chrome tries to download a 2.7GB file instead of making a range request.
=> Cast last_modified value to integer when comparing ifrange requests

CHANGELOG.md, wsgidav/request_server.py
https://github.com/mar10/wsgidav/blob/cec0d84222fc24bea01be1cea91729001963f172/wsgidav/request_server.py#L1624-L1634
Currently, fileobj.close() is never called when a client just drops the connection, as yielding throws a GeneratorExit exception.
=> Close file properly when client disconnects

wsgidav/server/server_cli.py
This adds SSL support for gevent. The missing Server header is not added, as this is only checked by one test case and I'm not sure it is the right way to implement it as I did in #157.
TODO: test if certificate chain option is working correctly.
=> Add SSL support for gevent.

README.md
Should install python-pam before using pam-login auth, otherwise will get an ImportError.
=> Add note for pam-login auth

CHANGELOG.md, Pipfile, Pipfile.lock, requirements.txt, setup.py, tox.ini, wsgidav/server/server_cli.py
The jsmin library is meant for minification of Javascript, not loading
of JSON files with comments. It's also not likely to see much
development in future because the author has little interest in
supporting ES6 etc.
The json5 library (and the cython version pyjson5) are both actually
supported upstream, and more accurately fulfil the requirement of being
able to use comments in JSON files.
=> Replace jsmin with json5 dependency

.travis.yml, CHANGELOG.md, tests/test_lock_manager.py, tox.ini, wsgidav/lock_manager.py, wsgidav/lock_storage_redis.py
This is a basic Redis lock storage. Maybe it is useful for others running multiple wsgidav instances.
Let me know what you think 😃
=> Redis lock storage implementation

CHANGELOG.md, wsgidav/request_server.py
Related to Issue #183 and pull request #187, also the Header HTTP_X_FORWARDED_HOST has to be checked in case of a reverse proxy call. 
EDIT: Removed wrong whitespaces
=> Check also HTTP_X_FORWARDED_HOST as alternative to DESTINATION header

CHANGELOG.md, wsgidav/dav_provider.py, wsgidav/fs_dav_provider.py, wsgidav/lock_man/lock_manager.py
Surely an oversight, in the recursive mode the child locks must be deleted. The "recursive" parameter must therefore be taken into account in the `get_url_lock_list` function
=> Fix removing locks in recursive mode

CHANGELOG.md, wsgidav/dav_provider.py
This change restores the ability to set the last modified date with getlastmodified within WinSCP and CarotDAV. Issue was first discussed in #248 
I might be completely off-base with this solution. I'm unsure how it was working correctly under any client without specifying the keyword.
=> Use the required dry_run keyword argument when calling set_last_modified

wsgidav/dav_provider.py
`_DAVResource.get_creation_date()` is annotated as returning `Optional[datetime]`, but `_DAVResources.get_property_value()` passes the method's return value to `get_rfc3339_time()`, which requires a Unix timestamp instead.
=> Fix return type annotation on `get_creation_date()`

docs/source/faq.rst
The pages in question were renamed in commit bfba2e74047c03d7da191a824642515dbb3e9abd.
=> Fix broken links in FAQ

CHANGELOG.md, Pipfile, docs/source/requirements.txt, requirements.txt, wsgidav/xml_tools.py
=> remove defusedxml.lxml

docs/source/user_guide_configure.rst, wsgidav/dc/pam_dc.py
In the current implementation, PAM authentication in wsgidav only checks if a user exists on the OS. The new patch introduces a user-list control feature, allowing more granular management of which users can access the WebDAV service.
1. **`deny_users` Option**:  
A `list[str]` that explicitly denies login access to any users listed. This option has the highest priority. If a user is listed in `deny_users`, they will be blocked from logging in, regardless of other settings.
2. **`allow_users` Option**:  
Can be set as a `str` or `list[str]`, determining which users are allowed to log in:
- **"all" (default)**: All users on the OS are permitted.
- **"current"**: Only the user running the wsgidav program can log in.
- A specific list of users can also be provided to explicitly allow access. …
=> User-List Control for PAM Authentication
