mar10/wsgidav

- wsgidav/request_server.py
Handle the chunk size integer value from Finder correctly and prevent another server side busy spin/hang in case the client chunk size from the HTTP header doesn't match the actual chunk payload.
> A more thorough solution to the Mac Finder upload/copy problem in issue 15

- wsgidav/http_authenticator.py
A patch to support commas in file names with clients that don't url-encode path in auth header.
Tested to fix handling of such files in Windows 7 file manager and in OSX Finder.
> Fix for issue #23: comma in file names

- wsgidav/fs_dav_provider.py
> proposed small API change to allow much easier per-user chrooting

- tests/test_util.py
Instead of importing all the functions of util it's better to only
import the functions that are used
> Avoid using import * on test_util

- tests/benchmarks.py
- tests/conftest.py
- tests/davclient.py
- tests/test_litmus.py
- tests/test_lock_manager.py
- tests/test_property_manager.py
- tests/test_scripted.py
- tests/test_util.py
- tests/test_wsgidav_app.py
- tests/util.py
- wsgidav/compat.py
- wsgidav/dav_error.py
- wsgidav/dav_provider.py
- wsgidav/debug_filter.py
- wsgidav/dir_browser.py
- wsgidav/domain_controller.py
- wsgidav/error_printer.py
- wsgidav/fs_dav_provider.py
- wsgidav/http_authenticator.py
- wsgidav/lock_manager.py
- wsgidav/lock_storage.py
- wsgidav/middleware.py
- wsgidav/property_manager.py
- wsgidav/request_resolver.py
- wsgidav/request_server.py
- wsgidav/rw_lock.py
- wsgidav/util.py
- wsgidav/wsgidav_app.py
- wsgidav/xml_tools.py
Initial run of `autopep8` for https://github.com/mar10/wsgidav/issues/43
Command run:
```shell
run autopep8 --in-place wsgidav/*.py tests/*.py
```
> Initial run of `autopep8`

- wsgidav/dav_provider.py
- wsgidav/request_server.py
We need the ability to add more custom headers (e.g. Content-Disposition).
This change will allow providers to modify the headers.
Accidentally closed the other pull request: https://github.com/mar10/wsgidav/pull/38
> Add ability to provide additional headers

- requirements-dev.txt
- tests/test_streaming.py
- tests/util.py
- tox.ini
- wsgidav/addons/filelike_queue.py
- wsgidav/addons/stream_tools.py
- wsgidav/compat.py
Sample and test for piping a PUT input stream to another consumer
> Streaming put

- CHANGELOG.md
- tests/test_streaming.py
- tests/util.py
- wsgidav/addons/stream_tools.py
- wsgidav/dav_provider.py
- wsgidav/request_server.py
Close #57 
Close #55 
Close #48 
Close #56
> Custom reqhandlers

- wsgidav/http_authenticator.py
https://github.com/mar10/wsgidav/issues/75
> ISSUE 75: Return 401 when auth method is not supported

- install_litmus.sh
webdav.org seems to have been shut down.
> Change install_litmus.sh to fetch from github

- CHANGELOG.md
- sample_wsgidav.yaml
- wsgidav/dav_provider.py
Support for Microsoft's Win32LastModifiedTime property. Other Win32 properties ignored, but return success.
> Limited support for Win32 modtime

- wsgidav/http_authenticator.py
fix #135 
test suite ran below. the continuous integration build failed (but it has the same output as your current build from master branch).
> digest authentication bug fix (v3.0.0a4)

- wsgidav/http_authenticator.py
This is in response to issue #137 
Enabled through new property `implements_realm_user_digest_hash` in `http_authenticator`.
If enabled then new optional domain_controller interface method `get_realm_user_password_hash`
must be implemented. 
```
def get_realm_user_digest_hash(self, realm_name, user_name):
"""
:param realm_name: string
:param user_name: string
:return: string, MD5 hash, MD5(user_name:realm:password)
"""
digest_hash = 'a4cb4d64edfe976a6df8d908aa0ff412' (stored in DB or API call)
return digest_hash
```
Sample Config (to enable feature):
```
config = {
'add_header_MS_Author_Via': True,  # necessary for MS Office Support
'provider_mapping': {'demo/webdav': '/vagrant/sample_docs'},
'verbose': 5,
'http_authenticator': {
'domain_controller': DomainController,
'accept_digest': …
```
> optional domain_controller interface method get_realm_user_digest_hash

- doc/sample_wsgidav.conf
- doc/sphinx/reference_guide_architecture.rst
- doc/sphinx/user_guide_configure.rst
- sample_wsgidav.yaml
- wsgidav/default_conf.py
- wsgidav/request_resolver.py
- wsgidav/request_server.py
- wsgidav/wsgidav_app.py
I've made some comments to better guide users how to enable dir browsing
related to #144
> better documentation for dir browsing

- wsgidav/request_server.py
> Fix for #152 "Accept-Ranges"

- wsgidav/request_server.py
I've added the requested path to the 404 log messages to allow better debugging
> request 404 error msg with requested path

- Dockerfile
final image reduction from 244MB to 66.4MB
> Docker image reduction from 244MB to 66.4MB

- wsgidav/util.py
Fix UTF8 surrogates, see https://github.com/mar10/wsgidav/issues/181
> Fixes UTF8 surrogates => mar10/wsgidav#181

- docs/sphinx/sample_wsgidav.json
- sample_wsgidav.yaml
- wsgidav/default_conf.py
- wsgidav/dir_browser/_dir_browser.py
Addresses #191 .
I haven't updated any docs or anything, didn't want to jump the gun!
> Allow `:dir_browser` `htdocs_path` to be specified in config.

- wsgidav/debug_filter.py
- wsgidav/util.py
see https://github.com/mar10/wsgidav/issues/198#issuecomment-751328877
> Fix #198 Cast REMOTE_PORT to string

- wsgidav/wsgidav_app.py
Few lines below there is a check:
https://github.com/mar10/wsgidav/blob/ca90c210a815576b0e7e467905b49a8b4fb22580/wsgidav/wsgidav_app.py#L279-L282
> Do not access optional domain_controller without check

- wsgidav/http_authenticator.py
> Fix exception whenever user access unknown realm

- CHANGELOG.md
- wsgidav/dav_provider.py
- wsgidav/fs_dav_provider.py
Add support for [RFC4331](http://www.webdav.org/specs/rfc4331.html) (`quota-used-bytes` and `quota-available-bytes`)
> Add quota-used-bytes and quota-available-bytes (RFC4331)

- docs/source/index.rst
anonymous was spelled wrongly in line 65
> Fixed spelling mistake in index.rst

- wsgidav/server/server_cli.py
> `--root` argument honors `fs_dav_provider` configuration
